### PR TITLE
CI/CD

### PR DESCRIPTION
**Pull request by jritsema**

### CODE REVIEW

**Comment by mickeyyawn** [comment]
Different than how I do it, but open to other ways.  I would personally not do the golang build in docker, but in a script from ci/cd, then add .  and  FROM Alpine (or scratch).  Keeps the image tight and small.  I don't know what the base is for golang 1.8.3 or how big an image that produces.

**Comment by jritsema** [comment]
This uses multi-stage build to produce a ~9mb image (would be smaller if we removed the gorilla deps and used stdlib).  I guess we could drop it in scratch rather than alpine to go even smaller.  Was planning on hooking this directly up to quay...hence the multi-stage Dockerfile vs build script.

**Comment by mickeyyawn** [comment]
OOHHHHH i'm a dork.  yes, now i see alpine at the bottom.  Carry on, nothing to see here.

**Comment by jritsema** [comment]
So `FROM scratch` shrunk it from 9.13MB to 6.26MB.

**Review by mickeyyawn — APPROVED** [review]
LGTM

**Review by jtolsma — APPROVED** [review]

**Pull request merged**
